name: Pretty Text - Pull Request Check

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  PR-Check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run linter
        run: cargo clippy --verbose

      - name: Build
        run: cargo build --verbose
